version: '2.1'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    volumes:
      - /home/users/mkociszewski/repositories/poc-schema-registry/data/zoo:/opt/zookeeper-3.4.13/data
    ports:
      - "2181:2181"
    mem_limit: 1G
  kafka_1:
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/kafka-logs-1
      KAFKA_BROKER_ID: 1
      KAFKA_HEAP_OPTS: "-XX:ParallelGCThreads=1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/users/mkociszewski/repositories/poc-schema-registry/data/storage1:/kafka/kafka-logs-1
    ports:
      - "8001:9092"
    mem_limit: 3G
  kafka_2:
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/kafka-logs-2
      KAFKA_BROKER_ID: 2
      KAFKA_HEAP_OPTS: "-XX:ParallelGCThreads=1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/users/mkociszewski/repositories/poc-schema-registry/data/storage2:/kafka/kafka-logs-2
    ports:
      - "8002:9092"
    mem_limit: 3G
  kafka_3:
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/kafka-logs-3
      KAFKA_BROKER_ID: 3
      KAFKA_HEAP_OPTS: "-XX:ParallelGCThreads=1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/users/mkociszewski/repositories/poc-schema-registry/data/storage3:/kafka/kafka-logs-3
    ports:
      - "8003:9092"
    mem_limit: 3G
  schema-registry:
    image: confluentinc/cp-schema-registry
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: localhost:8001,localhost:8002,localhost:8003
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
    depends_on:
      - zookeeper
      - kafka_1
      - kafka_2
      - kafka_3
